roles:
  seller:
    name: 'Sale'
    path_table: '/tables?only=open&type=SALE'
    path_meeting: '/meetings?type=SALE'
    path_statistics: '/statistics?type=SALE'
  hh:
    name: 'HH'
    path_table: '/tables?only=open&type=CANDIDATE'
    path_meeting: '/meetings?type=CANDIDATE'
    path_statistics: '/statistics?type=CANDIDATE'
admin:
  menu:
    sub menu one:
      name: 'Admin panel'
      item one:
        name: 'Active users'
        path: '/admin/users?status=unlock'
      item two:
        name: 'Bloked users'
        path: '/admin/users?status=lock'
      item dev one:
        divider: true
      item three:
        name: 'Sellers controls'
        path: '/admin/task_controls?type=SALE'
      item fore:
        name: 'HH controls'
        path: '/admin/task_controls?type=CANDIDATE'
      item five:
        name: 'Plans'
        path: '/plans'
