permissions:
  manage_sales:
      name: Sale
      path: '/tables?only=open&type=SALE'
  manage_candidates:
      name: HH
      path: '/tables?only=open&type=CANDIDATE'
  self_reports:
      name: Reports
      path: '/reports/reports_pointer'
  administration_section:
      name: Admin panel
      path: '/admin/admin_pointer'
