seller:
  menu:
    sub menu one:
      name: 'Tasks'
      item one: 
        name: 'Open tasks'
        path: '/tasks'
      item two: 
        name: 'Sold tasks'
        path: '/tasks?only=sold'
      item three: 
        name: 'Declined tasks'
        path: '/tasks?only=declined'
      divider: true
      item fore: 
        name: 'Export'
        path: '/export'
    sub menu two:
      name: 'Events'
      item one: 
        name: 'Meetings'
        path: '/meetings'
    sub menu three:
      name: 'Info'
      item one: 
        name: 'Statistic'
        path: '/statistics'
hr:
hh:
admin:
  menu:
    sub menu one:
      name: 'Sales'
      item one: 
        name: 'Open sales'
        path: '/tables?only=open&type=SALE'
      item two: 
        name: 'Sold sales'
        path: '/tables?only=sold&type=SALE'
      item three: 
        name: 'Declined sales'
        path: '/tables?only=declined&type=SALE'
      divider: true
      item fore: 
        name: 'Export'
        path: '/export'
      divider: true
      item five: 
        name: 'Meetings'
        path: '/meetings'
      divider: true
      item six: 
        name: 'Statistic'
        path: '/statistics'