seller:
  menu:
    sub menu one:
      name: 'Seller'
      item one: 
        name: 'Sales'
        path: '/tables?only=open&type=SALE'
      item dev one:
        divider: true
      item fore: 
        name: 'Export'
        path: '/export?type=SALE'
    sub menu two:
      name: 'Events'
      item one: 
        name: 'Meetings'
        path: '/meetings'
    sub menu three:
      name: 'Info'
      item one: 
        name: 'Statistic'
        path: '/statistics'
hr:
hh:
  menu:
    sub menu one:
      name: 'HH'
      item one: 
        name: 'Candidates'
        path: '/tables?only=open&type=CANDIDATE'
admin:
  menu:
    sub menu one:
      name: 'Seller'
      item one: 
        name: 'Sales'
        path: '/tables?only=open&type=SALE'
      item dev one:
        divider: true
      item fore: 
        name: 'Meetings'
        path: '/meetings'
      item dev three:
        divider: true
      item five: 
        name: 'Statistic'
        path: '/statistics'
      item dev fore:
        divider: true
      item six: 
        name: 'Export'
        path: '/export?type=SALE'
    sub menu two:
      name: 'HH'
      item one: 
        name: 'Candidates'
        path: '/tables?only=open&type=CANDIDATE'
    sub menu three:
      name: 'Admin panel'
      item one: 
        name: 'Active users'
        path: '/admin/users?status=unlock'
      item two: 
        name: 'Bloked users'
        path: '/admin/users?status=lock'
      item dev one:
        divider: true
      item three: 
        name: 'Sellers controls'
        path: '/admin/task_controls?type=SALE'
      item fore: 
        name: 'HH controls'
        path: '/admin/task_controls?type=CANDIDATE'