seller:
  menu:
    sub menu one:
      name: 'Tasks'
      item one: 
        name: 'Open tasks'
        path: '/tasks'
      item two: 
        name: 'Sold tasks'
        path: '/tasks?only=sold'
      item three: 
        name: 'Declined tasks'
        path: '/tasks?only=declined'
      divider: true
      item fore: 
        name: 'Export'
        path: '/export'
    sub menu two:
      name: 'Events'
      item one: 
        name: 'Meetings'
        path: '/meetings'
    sub menu three:
      name: 'Info'
      item one: 
        name: 'Statistic'
        path: '/statistics'
hr:
hh:
admin: